# Generated by Django 6.0.1 on 2026-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='api_task_client__955444_idx',
        ),
        migrations.RenameField(
            model_name='taskattachment',
            old_name='file',
            new_name='file_link',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Indicates if this organization is a client organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('department_head', 'Department Head'), ('employee', 'Employee'), ('client', 'Client')], default='employee', max_length=100),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='api_task_status_2aef03_idx'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='client_visible',
        ),
    ]
