# Generated by Django 6.0.1 on 2026-01-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_api_task_client__955444_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'is_client': False}, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'is_client': False}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='api.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_organizations',
            field=models.ManyToManyField(blank=True, help_text='Client organizations that can view/edit this task', limit_choices_to={'is_client': True}, related_name='accessible_tasks', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns/manages this task', limit_choices_to={'is_client': False}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(limit_choices_to={'is_client': False}, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('department_head', 'Department Head'), ('employee', 'Employee'), ('client', 'Client')], default='employee', max_length=100),
        ),
    ]
