# Generated by Django 6.0.1 on 2026-01-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_comment_taskcomment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_client': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organization'),
        ),
    ]
