# Generated by Django 6.0.1 on 2026-02-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_taskcomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('tenant', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('tenant', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcomment',
            unique_together={('tenant', 'id')},
        ),
    ]
