# Generated by Django 6.0.1 on 2026-02-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taskcomment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('tenant', 'name')},
        ),
    ]
